version: '3.7'

services:
  rss:
    image: ghcr.io/ssddanbrown/rss:v1.3.0
    container_name: rss
    environment:
      - APP_NAME=Tipi-RSS
      - APP_FEED_UPDATE_FREQUENCY=35
      - APP_LOAD_POST_THUMBNAILS=true
    volumes:
      - ${APP_DATA_DIR}/data/storage:/app/storage
    ports:
      - '${APP_PORT}:80'
    restart: unless-stopped
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.rss.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.rss.entrypoints: websecure
      traefik.http.routers.rss.service: rss
      traefik.http.routers.rss.tls.certresolver: myresolver
      traefik.http.services.rss.loadbalancer.server.port: 80
    networks:
      - tipi_main_network
