version: '3'

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.0.1
    container_name: sabnzbd
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/media/usenet:/media/usenet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.sabnzbd.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.sabnzbd.entrypoints: websecure
      traefik.http.routers.sabnzbd.service: sabnzbd
      traefik.http.routers.sabnzbd.tls.certresolver: myresolver
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
