version: "3"

services:
  movary:
    image: leepeuker/movary:0.51.0
    container_name: movary
    environment:
      - TMDB_API_KEY=${MOVARY_TMDB_API_KEY}
      - TIMEZONE=${TZ}
      - DATABASE_MODE=mysql
      - DATABASE_MYSQL_HOST=movary-db
      - DATABASE_MYSQL_NAME=movary
      - DATABASE_MYSQL_USER=tipi
      - DATABASE_MYSQL_PASSWORD=${MOVARY_MYSQL_PASSWORD}
      - TMDB_ENABLE_IMAGE_CACHING=1
    restart: unless-stopped
    command: "php bin/console.php database:migration:migrate"
    volumes:
      - ${APP_DATA_DIR}/data/movary:/app/storage
    ports:
      - ${APP_PORT}:80
    depends_on:
      - movary-db
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.movary.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.movary.entrypoints: websecure
      traefik.http.routers.movary.service: movary
      traefik.http.routers.movary.tls.certresolver: myresolver
      traefik.http.services.movary.loadbalancer.server.port: 80

  movary-db:
    image: linuxserver/mariadb:latest
    environment:
      MYSQL_DATABASE: "movary"
      MYSQL_USER: "tipi"
      MYSQL_PASSWORD: ${MOVARY_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MOVARY_MYSQL_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mysql:/config
    networks:
      - tipi_main_network
