version: "3.8"

services:
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:2.1.3
    ports:
      - ${APP_PORT}:5690
    volumes:
      - ${APP_DATA_DIR}/data/database:/data/database
    environment:
      - APP_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=${TZ}
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.wizarr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.wizarr.entrypoints: websecure
      traefik.http.routers.wizarr.service: wizarr
      traefik.http.routers.wizarr.tls.certresolver: myresolver
      traefik.http.services.wizarr.loadbalancer.server.port: 5690


